---

- name: install nginx
  apt: 
    name: nginx
    update_cache: yes

- name: config nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: clear var www html
  file:
    path: /var/www/html/*
    state: absent
  notify: restart nginx