---

- name: Install webdev
  hosts: webdev
  become: true
  tasks:
    
    - name: Install nginx
      user:
        name: www-data
        comment: www data
        uid: 1040

    - name: Install nginx
      apt:
        name: nginx
        update_cache: yes
    
    - name: Clean default vhost available
      file:
        state: absent
        path: "/etc/nginx/sites-available/"
      
    - name: Clean default vhost enabled
      file:
        state: absent
        path: "/etc/nginx/sites-enabled/"
    
    - name: Clean html
      file:
        state: absent
        path: "/var/www/html/"
   
    - name: Create dir vhost available
      file:
        state: directory
        path: /etc/nginx/sites-available/
   
    - name: Create dir vhost enable
      file:
        state: directory
        path: /etc/nginx/sites-enabled
   
    - name: Create dir vhost html
      file:
        state: directory
        owner: "www-data"
        group: "www-data"
        mode: 0755        
        path: /var/www/html/

    - name: Config nginx.conf
      copy:
        src: /home/desk/workflow/_ops/test-ops/files/nginx/nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: 0644
        force: yes

    - name: Config vhost nginx
      copy:
        src: /home/desk/workflow/_ops/test-ops/files/nginx/vhost_default_80
        dest: /etc/nginx/sites-available/default.conf
        owner: root
        group: root
        mode: 0644
        force: yes
     
    - name: Symlink vhost
      file:
        src: /etc/nginx/sites-available/default.conf
        dest: /etc/nginx/sites-enabled/default.conf
        owner: root
        group: root
        state: link
      notify: Reload Nginx     

    - name: Install php-fpm
      apt:
        name: php-fpm
        update_cache: yes
        
    - name: Config www.conf
      copy:
        src: /home/desk/workflow/_ops/test-ops/files/php/www.conf
        dest: /etc/php/7.0/fpm/pool.d/www.conf
        owner: root
        group: root
        mode: 0644
        force: yes
      
    - name: Config php.ini
      copy:
        src: /home/desk/workflow/_ops/test-ops/files/php/php7.0
        dest: /etc/php/7.0/fpm/php.ini
        owner: root
        group: root
        mode: 0644
        force: yes
      notify: Reload php7.0-fpm

    - name: Downloads WordPress
      get_url: 
        url: https://wordpress.org/latest.tar.gz 
        dest: /tmp/wordpress.tar.gz
        validate_certs: no

    - name: Extract WordPress
      unarchive: 
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html
        copy: no
        owner: www-data
        group: www-data
        mode: 0755
      become: yes
      notify: Reload php7.0-fpm

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: restarted

    - name: Reload php7.0-fpm
      service:
        name: php7.0-fpm
        state: restarted

- name: Install databaseDev
  hosts: databaseDev
  become: true
  tasks:

    - name: install mysql
      apt: 
        name: mysql-server
        update_cache: yes

  handlers:
    - name: Reload mysql
      service:
        name: mysql
        state: restarted